version: "3.8"
services:

  postgres:
    image: postgres:alpine
    container_name: "postgres"
    volumes:
    - ./app/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: demo_products
    ports:
      - "5432:5432"

  api:
    container_name: "api"
    depends_on:
      - postgres
    volumes:
      - ./app/api:/api
      - /api/node_modules
    build:
      context: .
      dockerfile: ./api.Dockerfile
    environment:
      - DB_CONNECT=postgres://user:pass@postgres/demo_products
      - SESSION_COOKIE_NAME=demo_products_api_session
      - SESSION_SECRET=iTsOuRsEcReTnEvErTeAcHtHeWuTaNg
      - CORS_ALLOW_ORIGIN=http://localhost:8000
      - PORT=3000
      - NODE_ENV=development
    ports:
      - "3000:3000"
    command: npm run start:dev

  gatsby:
    container_name: "gatsby"
    depends_on:
      - "postgres"
      - "api"
    volumes:
      - ./app/gatsby:/gatsby
      - /gatsby/node_modules
    build:
      context: .
      dockerfile: ./gatsby.Dockerfile
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/
      - GATSBY_CART_API_URL=http://localhost:3000
      - DB_CONNECT=postgres://user:pass@postgres/demo_products
    ports:
      - "8000:8000"
      - "9000:9000"
      - "6006:6006"
      - "9929:9929"
      - "9230:9230"
      - "36515:36515"
      - "34085:34085"
    command: npm start
