INSERT INTO public.products("id","title","description","price","vendor_id","image_url")
VALUES
(1,E'Explosive Tennis Balls',E'1 Dozen Explosive Tennis Balls. Tickle your friends! Surprise your opponent!',E'$14.99',1,E'https://vignette.wikia.nocookie.net/looneytunes/images/a/ad/Explosive_Tennis_Balls.png'),
(2,E'Anvil',E'1 Large Acme Anvil. Great for dropping on things.',E'$149.99',1,E'https://images-na.ssl-images-amazon.com/images/I/91%2BWXXaw9KL._AC_SL1500_.jpg'),
(3,E'Matches',E'Regular, everyday matches, good for igniting things.',E'$0.99',1,E'https://vignette.wikia.nocookie.net/looneytunes/images/a/aa/Matches.png'),
(4,E'Rocket-Powered Roller Skates',E'1 Pair of Acme Rocket-Powered Roller Skates. Let you skate at unlimited speed.',E'$59.99',1,E'https://vignette.wikia.nocookie.net/looneytunes/images/7/74/RocketSkates.png'),
(5,E'Bird Seed',E'Acme Bird Seed Ver. 1. Part of a bird\'s nutritious meal.',E'$4.99',1,E'https://vignette.wikia.nocookie.net/looneytunes/images/d/d4/Bird_Seed_Box_Ver._1.png'),
(6,E'Giant Rubber Band',E'Acme Giant Rubber Band. Used for giant aerial slingshots to shoot things.',E'$49.99',1,E'https://vignette.wikia.nocookie.net/looneytunes/images/f/f2/Giant_Rubber_Band_V3.png'),
(7,E'Dehydrated Boulders',E'Makes instant boulders with just a drop of water.',E'$39.99',1,E'https://vignette.wikia.nocookie.net/looneytunes/images/7/76/Dehydrated_Boudlers.png'),
(8,E'Earthquake Pills',E'Acme Earthquake Pills. Why wait? Make your own Earthquakes. Loads of fun!',E'$29.99',1,E'https://vignette.wikia.nocookie.net/looneytunes/images/b/b3/Earthquake_Pills.png'),
(9,E'Cactus Costume',E'From Acme Costume Co. Disguise yourself as a cactus and scare others.',E'$79.99',1,E'https://vignette.wikia.nocookie.net/looneytunes/images/1/11/Cactus_Costume.png'),
(10,E'Jet-Propelled Unicycle',E'Acme Jet-Propelled Unicycle',E'$299.99',1,E'https://vignette.wikia.nocookie.net/looneytunes/images/1/13/Jet-Propelled_Unicycle.png'),
(11,E'Instant Road',E'Acme Instant Road. Rolls out easily.',E'$99.99',1,E'https://vignette.wikia.nocookie.net/looneytunes/images/0/0d/Instant_Road2.png'),
(12,E'Zap Trap',E'Acme Zap Trap.',E'$89.99',1,E'https://vignette.wikia.nocookie.net/looneytunes/images/3/39/Zap_Trap.png'),
(13,E'School of Boxing',E'Acme School of Boxing. Audio Course. Vinyl.',E'$49.99',1,E'https://vignette.wikia.nocookie.net/looneytunes/images/1/19/ACME_School_of_Boxing-1.png'),
(14,E'Leg Muscle Vitamins',E'Acme Triple-Strength Fortified Leg Muscle Vitamins. Family Size. Gives your legs the vitamins it needs to run faster than ever before!',E'$19.99',1,E'https://vignette.wikia.nocookie.net/looneytunes/images/8/8c/Leg_Muscle_Vitamins.png'),
(15,E'Glue',E'Acme Glue. A real sticky adhesive.',E'$8.99',1,E'https://vignette.wikia.nocookie.net/looneytunes/images/0/01/Glue_V1.png'),
(16,E'Bumble Bees',E'Acme Bumble Bees. One Fifth.',E'$9.99',1,E'https://vignette.wikia.nocookie.net/looneytunes/images/a/af/Bumble_Bees.png'),
(17,E'Tornado Kit',E'Acme Do-It-Yourself Tornado Kit. Lets you "seed" your own tornadoes.',E'$24.99',1,E'https://vignette.wikia.nocookie.net/looneytunes/images/0/0b/Tornado_Kit.png'),
(18,E'Hi-Speed Tonic',E'Acme Hi-Speed Tonic. Contains Vitamins R-P & M. Lets one run super fast.',E'$14.99',1,E'https://vignette.wikia.nocookie.net/looneytunes/images/7/71/Hi-Speed_Tonic.png'),
(19,E'Jet-Propelled Pogo Stick',E'Acme Jet-Propelled Pogo Stick.',E'$29.99',1,E'https://vignette.wikia.nocookie.net/looneytunes/images/4/4d/Jet-Propelled_Pogo-Stick.png'),
(20,E'Instant Awakener',E'Acme Instant Awakener.',E'$19.99',1,E'https://vignette.wikia.nocookie.net/looneytunes/images/3/3b/Instant_Awakener.png'),
(21,E'Bed Springs',E'Acme Bed Springs. Put a spring in your step!',E'$12.99',1,E'https://vignette.wikia.nocookie.net/looneytunes/images/6/6f/Bed_Springs.png'),
(22,E'Rocket Sled Kit',E'Little Giant Do-It-Yourself Rocket Sled Kit',E'$899.99',1,E'https://vignette.wikia.nocookie.net/looneytunes/images/3/36/Little-Giant_Do-It-Yourself_Rocket_Sled_Kit.png'),
(23,E'Fire Crackers',E'1 Dozen Acme Little Giant-Giant Fire Crackers',E'$17.99',1,E'https://vignette.wikia.nocookie.net/looneytunes/images/3/30/Little-Giant_Fire_Crackers.png'),
(24,E'Giant Fly Paper',E'Acme Brand Giant Fly Paper',E'$15.99',1,E'https://vignette.wikia.nocookie.net/looneytunes/images/6/60/Giant_Fly_Paper.png'),
(25,E'Atom Re-Arranger',E'Acme Atom Re-Arranger',E'$79.99',1,E'http://acme.com/catalog/atom.jpg'),
(26,E'Out-Board Motor',E'One Acme Out-Board Motor',E'$699.99',1,E'http://acme.com/catalog/out.jpg'),
(27,E'Toothpicks',E'Acme Toothpicks are manufactured by a revolutionary patented process.',E'$0.99',1,E'http://acme.com/catalog/tooth.jpg'),
(28,E'Instant Feathers',E'If a chicken you know has lost its feathers due to a freak accident, use Acme Instant Feathers to make them complete again.',E'$3.99',1,E'http://acme.com/catalog/instantfeathers.jpg'),
(29,E'Super Outfit',E'Does not give one the ability to fly.',E'$24.99',1,E'https://vignette.wikia.nocookie.net/looneytunes/images/6/64/Super_Outfit.png'),
(30,E'Thneed',E'A Thneed is a thing that everyone needs.',E'$79.99',2,E'https://vignette.wikia.nocookie.net/seuss/images/0/08/Thneed_front.PNG');
